default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: hoge
  password: hogehoge
  database: budgetter_development

development:
  <<: *default
  database: budgetter_development
  host: 127.0.0.1
  port: 3306

test:
  <<: *default
  username: hoge
  password: hogehoge
  database: budgetter_test

production:
  <<: *default
  username: hoge
  password: hogehoge
  database: budgetter
